SET C51INC=D:\Keil uVision5\C51\Inc;D:\Keil uVision5\C51\Inc\Atmel
SET C51LIB=D:\Keil uVision5\C51\Lib
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Microchip
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"D:\Keil uVision5\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"D:\Keil uVision5\C51\BIN\C51.EXE" @".\Objects\BUZZER~1.__I"
"D:\Keil uVision5\C51\BIN\C51.EXE" @".\Objects\Delay.__i"
"D:\Keil uVision5\C51\BIN\C51.EXE" @".\Objects\main.__i"
"D:\Keil uVision5\C51\BIN\C51.EXE" @".\Objects\tft_cat.__i"
"D:\Keil uVision5\C51\BIN\LIB51.EXE" @".\Objects\FakeVidio_CatDance.__b"
